//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementTool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignResource
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string UserId { get; set; }
        public string AssignerId { get; set; }
    
        public virtual Project Project { get; set; }
    }
}
